# Generated by Django 4.0.5 on 2022-06-09 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='password',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keepass.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.TextField(default='<django.db.models.fields.TextField>', max_length=100),
        ),
        migrations.AlterField(
            model_name='password',
            name='destination_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='password',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='password',
            name='username',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='masterpassword',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=100),
        ),
    ]
