# Generated by Django 4.0.4 on 2022-06-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepass', '0002_remove_password_user_id_remove_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
